import { Suspense } from "react"
import "../../styles/uswds/styles.scss"
import Loading from "./loading"
export const metadata = {
  title: "The Brooklyn Rail",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  )
}
