import "../../styles/uswds/styles.scss"
export const metadata = {
  title: "The Brooklyn Rail",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
