import "../../styles/uswds/styles.scss"
export const metadata = {
  title: "The Brooklyn Rail",
  description: "Generated by Next.js",
}

export default function Loading() {
  // You can add any UI inside Loading, including a Skeleton.
  return <>TKTK...</>
}
